"use client";
import React, { useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { toast } from 'sonner';

function LoginContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const role = searchParams.get('role') || 'intern';
  const isAdmin = role === 'admin';

  const [step, setStep] = useState<'email' | 'otp'>('email');
  const [email, setEmail] = useState("");
  const [otp, setOtp] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSendCode = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const res = await fetch("/api/auth/send-otp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, role: isAdmin ? "ADMIN" : "INTERN", isRegister: false })
      });
      
      const data = await res.json();
      
      if (!res.ok) {
        throw new Error(data.error || "Failed to send OTP");
      }

      setStep('otp');
      toast.success("6-digit code sent to your email!");
    } catch (err: any) {
      toast.error(err.message || "An error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  const handleVerifyCode = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const res = await fetch("/api/auth/verify-otp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, otp })
      });
      
      const data = await res.json();
      
      if (!res.ok) {
        throw new Error(data.error || "Invalid OTP");
      }

      toast.success("Successfully verified! Logging you in...");
      // Redirect to the magic link URL generated by the backend
      window.location.href = data.url;
    } catch (err: any) {
      toast.error(err.message);
      setIsLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-[#e0e5ec] flex items-center justify-center p-6">
      <div className="w-full max-w-md bg-white border-4 border-black rounded-3xl p-8 shadow-[8px_8px_0_0_rgba(0,0,0,1)] relative">
        
          {/* TOGGLE BAR */}
          <div className="flex bg-slate-100 rounded-full p-1 border-2 border-black mb-8 w-full max-w-[250px] mx-auto shadow-[2px_2px_0_0_rgba(0,0,0,1)]">
            <button 
              onClick={() => router.push('/login?role=intern')}
              type="button"
              className={`flex-1 text-xs font-bold uppercase tracking-widest py-2 rounded-full transition-all ${!isAdmin ? 'bg-[#00f2fe] text-slate-900 border-2 border-black shadow-[2px_2px_0_0_rgba(0,0,0,1)]' : 'text-slate-500 hover:text-slate-900'}`}
            >
              Intern
            </button>
            <button 
              onClick={() => router.push('/login?role=admin')}
              type="button"
              className={`flex-1 text-xs font-bold uppercase tracking-widest py-2 rounded-full transition-all ${isAdmin ? 'bg-[#8A2BE2] text-white border-2 border-black shadow-[2px_2px_0_0_rgba(0,0,0,1)]' : 'text-slate-500 hover:text-slate-900'}`}
            >
              Admin
            </button>
          </div>

          <h1 className="text-3xl font-black uppercase tracking-tighter text-slate-900 mb-2 text-center">
          {isAdmin ? "Admin Login" : "Intern Login"}
        </h1>
        <p className="text-slate-500 mb-8 font-bold tracking-widest text-xs uppercase text-center">
          Sign in to your Belvo workspace
        </p>

        {step === 'email' ? (
          <form onSubmit={handleSendCode} className="space-y-4">
            <div>
              <label className="block text-sm font-bold uppercase tracking-widest mb-1 text-slate-900">Email</label>
              <input 
                type="email" 
                required
                value={email}
                onChange={e => setEmail(e.target.value)}
                className={`w-full border-2 border-black rounded-xl p-3 focus:outline-none shadow-[2px_2px_0_0_rgba(0,0,0,1)] text-slate-900 placeholder-slate-400 ${isAdmin ? 'focus:border-[#8A2BE2]' : 'focus:border-[#00f2fe]'}`}
                placeholder={isAdmin ? "admin@belvo.com" : "intern@belvo.com"}
              />
            </div>
            
            <button 
              disabled={isLoading}
              className={`w-full text-white font-bold py-3 rounded-xl border-2 border-black shadow-[4px_4px_0_0_rgba(0,0,0,1)] transition-all disabled:opacity-50 mt-4 ${
                isAdmin 
                  ? 'bg-[#8A2BE2] hover:bg-[#7a20c9] hover:translate-y-1 hover:shadow-[2px_2px_0_0_rgba(0,0,0,1)]' 
                  : 'bg-[#00f2fe] text-slate-900 hover:bg-[#00d2dd] hover:translate-y-1 hover:shadow-[2px_2px_0_0_rgba(0,0,0,1)]'
              }`}
            >
              {isLoading ? "Sending Code..." : "Send Secure Code"}
            </button>
          </form>
        ) : (
          <form onSubmit={handleVerifyCode} className="space-y-4">
            <div>
              <label className="block text-sm font-bold uppercase tracking-widest mb-1 text-slate-900">Enter 6-Digit Code</label>
              <input 
                type="text" 
                required
                value={otp}
                onChange={e => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))}
                className={`w-full border-2 border-black rounded-xl p-3 text-center tracking-[0.5em] font-bold text-2xl focus:outline-none shadow-[2px_2px_0_0_rgba(0,0,0,1)] text-slate-900 ${isAdmin ? 'focus:border-[#8A2BE2]' : 'focus:border-[#00f2fe]'}`}
                placeholder="000000"
              />
            </div>
            
            <button 
              disabled={isLoading || otp.length !== 6}
              className={`w-full text-white font-bold py-3 rounded-xl border-2 border-black shadow-[4px_4px_0_0_rgba(0,0,0,1)] transition-all disabled:opacity-50 mt-4 ${
                isAdmin 
                  ? 'bg-[#8A2BE2] hover:bg-[#7a20c9] hover:translate-y-1 hover:shadow-[2px_2px_0_0_rgba(0,0,0,1)]' 
                  : 'bg-[#00f2fe] text-slate-900 hover:bg-[#00d2dd] hover:translate-y-1 hover:shadow-[2px_2px_0_0_rgba(0,0,0,1)]'
              }`}
            >
              {isLoading ? "Verifying..." : "Verify & Login"}
            </button>

            <button 
              type="button"
              onClick={() => setStep('email')}
              className="w-full mt-2 text-sm font-bold text-slate-500 hover:text-slate-900 uppercase tracking-widest"
            >
              Back
            </button>
          </form>
        )}

        {isAdmin && (
          <p className="mt-6 text-center text-sm font-medium">
            Don't have an admin account? <Link href="/register" className="text-[#8A2BE2] hover:underline">Sign up</Link>
          </p>
        )}
      </div>
    </main>
  );
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#e0e5ec] flex items-center justify-center">Loading...</div>}>
      <LoginContent />
    </Suspense>
  );
}
